config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	resources :products do
    resources :comments
  end

  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about', to: 'static_pages#about'

  get 'static_pages/contact', to: 'static_pages#contact'

  get 'static_pages/index', to: 'static_pages#index'

  post 'static_pages/thank_you', to: 'static_pages#thank_you'

  root 'static_pages#homepage'

	post 'payments/create', to:'payments#create'

	mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Nameofapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:700,800|Raleway:200,400" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

  <body>
    <!-- start navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
            <span class="icon-bar">
            </span>
          </button>
          <div class="main-title navbar-brand">
            <%= link_to "Fahrradkit", root_path %>
          </div>
        </div>
        <!-- end navbar-header -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <li class="">
              <%= link_to "Products", products_path %>
            </li>
            <li class="">
              <%= link_to "About", static_pages_about_path %>
            </li>
            <li class="">
              <%= link_to "Contact", static_pages_contact_path %>
            </li>
            <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
            </li>
          </ul>

        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <li class="">
              <%= form_tag("/products", method: "get") do %>
                  <%= text_field_tag(:q) %>
                  <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                <% end %>
            </li>
          </ul>
         </div>
      </div>
      <!-- end navbar container -->
    </nav>
    <!-- end navbar -->
   <!-- flash notice -->


       <% if notice %>
        <p id="notice" class="notice alert alert-info"><%= notice %></p>
        <% end %>

        <% if alert %>
        <p id="alert" class="alert alert-info"><%= alert %></p>
        <% end %>

    <!-- flash notice -->
		<%= yield %>
    <footer class="footer">
      <div>
        <p class="text-muted">&copy; 2017 Fahrradkit Berlin</p>
      </div>
    </footer>

  </body>
</html>